# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: NGA LTER IM Documentation
email: chris@axiomdatascience.com
description: >- # this means to ignore newlines until "baseurl:"
  All things IM for the NGA site will be documented here. Sounds great!
baseurl: "nga-im-docs/" # the subpath of your site, e.g. /blog
url: "https://github.com/nga-lter/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: 
github_username:  nga-lter
instagram_username: nga.lter
# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
 # - titles_from_headings:
 #     enabled: true
 #     strip_title: true
 #     collections: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
